project:
  type: website
  output-dir: docs
  
website:
  title: "Omar Mnfy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dataviz.qmd
        text: Data Viz

output: 
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
    highlight: tango
    self_contained: false
    includes:
      before_body: "favicon.rhtml"
      
editor: visual

