project:
  type: website
  output-dir: docs
  
website:
  title: "Omar Mnfy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dataviz.qmd
        text: Data Viz

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    self_contained: false
    includes:
      in_header: "favicon.html"
      
editor: visual

