project:
  type: website
  output-dir: docs
  
website:
  title: "Omar Mnfy"
  navbar:
    left:
      - href: index.html
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

